eureka:
  instance:
    hostname:  xxl-job-admin
    prefer-ip-address: true
  client: # \u670D\u52A1\u63D0\u4F9B\u8005provider\u6CE8\u518C\u91D1eureka\u670D\u52A1\u5217\u8868\u5185
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://127.0.0.1:8090/eureka/