server:
  port: 8093
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # \u5F00\u542F\u4ECE\u6CE8\u518C\u4E2D\u5FC3\u52A8\u6001\u521B\u5EFA\u8DEF\u7531\u7684\u529F\u80FD\uFF0C\u5229\u7528\u5FAE\u670D\u52A1\u540D\u8FDB\u884C\u8DEF\u7531"

      routes:
        - id: study-service #payment_routh #路由的ID，没有固定规则，但要求唯一，建议配合服务名
          #uri: http://localhost:8761  #匹配后提供服务的路由地址 没有进行负载均衡
          uri: lb://study-service #匹配后提供服务的路由地址-------这里用的动态路由格式统一为 lb://注册进eureka服务中心的名字
          predicates:
            - Path=/study/** #断言，路径相匹配的进行路由--------断言也就是匹配方式，当识别到/servero1/**时就会跳转上面的uri
          filters:   #这个必须写
            - StripPrefix=1  #  请求/name/bar/foo，去除掉前面两个前缀之后，最后转发到目标服务的路径为/foo-----这里写的是只去掉一个，多了自然会导致路径错误，不同的访问url配置也不同

        - id: eureka-service #payment_routh #\u8DEF\u7531\u7684ID\uFF0C\u6CA1\u6709\u56FA\u5B9A\u89C4\u5219\uFF0C\u4F46\u8981\u6C42\u552F\u4E00\uFF0C\u5EFA\u8BAE\u914D\u5408\u670D\u52A1\u540D
          #uri: http://localhost:8761  #\u5339\u914D\u540E\u63D0\u4F9B\u670D\u52A1\u7684\u8DEF\u7531\u5730\u5740 \u6CA1\u6709\u8FDB\u884C\u8D1F\u8F7D\u5747\u8861
          uri: lb://eureka-service #\u5339\u914D\u540E\u63D0\u4F9B\u670D\u52A1\u7684\u8DEF\u7531\u5730\u5740-------\u8FD9\u91CC\u7528\u7684\u52A8\u6001\u8DEF\u7531\u683C\u5F0F\u7EDF\u4E00\u4E3A lb://\u6CE8\u518C\u8FDBeureka\u670D\u52A1\u4E2D\u5FC3\u7684\u540D\u5B57
          predicates:
            - Path=/server01/** #\u65AD\u8A00\uFF0C\u8DEF\u5F84\u76F8\u5339\u914D\u7684\u8FDB\u884C\u8DEF\u7531--------\u65AD\u8A00\u4E5F\u5C31\u662F\u5339\u914D\u65B9\u5F0F\uFF0C\u5F53\u8BC6\u522B\u5230/servero1/**\u65F6\u5C31\u4F1A\u8DF3\u8F6C\u4E0A\u9762\u7684uri
#          filters:   #\u8FD9\u4E2A\u5FC5\u987B\u5199
#            - StripPrefix=1  #  \u8BF7\u6C42/name/bar/foo\uFF0C\u53BB\u9664\u6389\u524D\u9762\u4E24\u4E2A\u524D\u7F00\u4E4B\u540E\uFF0C\u6700\u540E\u8F6C\u53D1\u5230\u76EE\u6807\u670D\u52A1\u7684\u8DEF\u5F84\u4E3A/foo-----\u8FD9\u91CC\u5199\u7684\u662F\u53EA\u53BB\u6389\u4E00\u4E2A\uFF0C\u591A\u4E86\u81EA\u7136\u4F1A\u5BFC\u81F4\u8DEF\u5F84\u9519\u8BEF\uFF0C\u4E0D\u540C\u7684\u8BBF\u95EEurl\u914D\u7F6E\u4E5F\u4E0D\u540C

eureka:
  instance:
    hostname:  cloud-gateway-service
    prefer-ip-address: true
  client: # \u670D\u52A1\u63D0\u4F9B\u8005provider\u6CE8\u518C\u91D1eureka\u670D\u52A1\u5217\u8868\u5185
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://127.0.0.1:8099/eureka/