server:
  port: 8092
  servlet:
    session:
      timeout: 30m
  tomcat:
    uri-encoding: utf-8
spring:
  application:
    name: study-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    password: zj123456
    url: jdbc:mysql://127.0.0.1:3306/my_test?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
  redis:
    host: 127.0.0.1
    port: 6379
    database: 2
    password:      # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接


eureka:
  instance:
    hostname: study-service
    prefer-ip-address: true
  client: # 服务提供者provider注册金eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://127.0.0.1:8090/eureka/
